DROP TABLE IF EXISTS ads_mms.training_data_store_skc_week_merge;


CREATE TABLE IF NOT EXISTS ads_mms.training_data_store_skc_week_merge (
    store_code                              VARCHAR         COMMENT '门店编号',
    skc_code                                VARCHAR         COMMENT 'skc编号',
    year_code                               VARCHAR         COMMENT '年',
    week_code                               VARCHAR         COMMENT '周',
    year_week_code                          VARCHAR         COMMENT '年-周',
    prev_year_week_code                     VARCHAR         COMMENT '上一次交易所处年-周',
    interval_weeks_to_prev                  INTEGER         COMMENT '距离上一次交易周数',
    list_dates_year_code                    VARCHAR         COMMENT '上市年',
    list_dates_week_code                    VARCHAR         COMMENT '上市周',
    list_dates_year_week_code               VARCHAR         COMMENT '上市年-周',
    interval_weeks_to_list                  INTEGER         COMMENT '距离上市时间周数',
    -- 门店相关
    city_name                               VARCHAR         COMMENT '城市名',
    area_code                               VARCHAR         COMMENT '地区编码(邮政编码)',
    sales_channel                           VARCHAR         COMMENT '销售类型',
    store_type                              VARCHAR         COMMENT '门店类型',
    store_level                             VARCHAR         COMMENT '门店等级',
    store_retail_amount_highest_8week       DECIMAL(18, 2)  COMMENT '门店8周内的最高零售价',
    store_retail_amount_lowest_8week        DECIMAL(18, 2)  COMMENT '门店8周内的最低零售价',
    store_retail_amount_mean_8week          DECIMAL(18, 2)  COMMENT '门店8周内平均零售价',
    store_retail_amount_gap_8week           DECIMAL(18, 2)  COMMENT '门店8周内最高最低零售价差值',
    store_sales_amount_highest_8week        DECIMAL(18, 2)  COMMENT '门店8周内最高销售价',
    store_sales_amount_lowest_8week         DECIMAL(18, 2)  COMMENT '门店8周内最低销售价',
    store_sales_amount_mean_8week           DECIMAL(18, 2)  COMMENT '门店8周内平均销售价',
    store_sales_amount_gap_8week            DECIMAL(18, 2)  COMMENT '门店8周内最高最低销售价差值',     
    store_discount_rate_mean_8week          DECIMAL(18, 2)  COMMENT '门店8周内的平均折扣率',
    -- skc相关
    main_cate                               VARCHAR         COMMENT '大类',
    sub_cate                                VARCHAR         COMMENT '中类',
    leaf_cate                               VARCHAR         COMMENT '小类',
    leaf_cate_retail_amount_highest_8week   DECIMAL(18, 2)  COMMENT '小类8周内最高零售价',
    leaf_cate_retail_amount_lowest_8week    DECIMAL(18, 2)  COMMENT '小类8周内最低零售价',
    leaf_cate_retail_amount_mean_8week      DECIMAL(18, 2)  COMMENT '小类8周内平均零售价',
    leaf_cate_retail_amount_gap_8week       DECIMAL(18, 2)  COMMENT '小类8周内最高最低零售价差值',
    leaf_cate_sales_amount_highest_8week    DECIMAL(18, 2)  COMMENT '小类8周内最高销售价',
    leaf_cate_sales_amount_lowest_8week     DECIMAL(18, 2)  COMMENT '小类8周内最低销售价',
    leaf_cate_sales_amount_mean_8week       DECIMAL(18, 2)  COMMENT '小类8周内平均销售价',
    leaf_cate_sales_amount_gap_8week        DECIMAL(18, 2)  COMMENT '小类8周内最高最低销售价差值',     
    leaf_cate_discount_rate_mean_8week      DECIMAL(18, 2)  COMMENT '小类8周内的平均折扣率',
    color_code                              VARCHAR         COMMENT '颜色编码',
    lining                                  VARCHAR         COMMENT '面料',
    customer_level_1_last_week              INTEGER         COMMENT '上周到店交易lv1的顾客数',
    customer_level_2_last_week              INTEGER         COMMENT '上周到店交易lv2的顾客数',
    customer_level_3_last_week              INTEGER         COMMENT '上周到店交易lv3的顾客数',
    customer_level_1_proportion_last_week   DECIMAL(18, 2)  COMMENT '上周到店交易lv1的顾客占比',
    customer_level_2_proportion_last_week   DECIMAL(18, 2)  COMMENT '上周到店交易lv2的顾客占比',
    customer_level_3_proportion_last_week   DECIMAL(18, 2)  COMMENT '上周到店交易lv3的顾客占比',
    customer_level_1_last_2week             INTEGER         COMMENT '上2周到店交易lv1的顾客数',
    customer_level_2_last_2week             INTEGER         COMMENT '上2周到店交易lv2的顾客数',
    customer_level_3_last_2week             INTEGER         COMMENT '上2周到店交易lv3的顾客数',
    customer_level_1_proportion_last_2week  DECIMAL(18, 2)  COMMENT '上2周到店交易lv1的顾客占比',
    customer_level_2_proportion_last_2week  DECIMAL(18, 2)  COMMENT '上2周到店交易lv2的顾客占比',
    customer_level_3_proportion_last_2week  DECIMAL(18, 2)  COMMENT '上2周到店交易lv3的顾客占比',
    customer_level_1_gap                    INTEGER         COMMENT '上周与上2周lv1顾客交易的差值',
    customer_level_2_gap                    INTEGER         COMMENT '上周与上2周lv2顾客交易的差值',
    customer_level_3_gap                    INTEGER         COMMENT '上周与上2周lv3顾客交易的差值',
    special_day_type                        VARCHAR         COMMENT '特殊日期类型',
    -- 天气
    weather_day_most                        VARCHAR         COMMENT '一周出现最多的日间天气类型',
    weather_night_most                      VARCHAR         COMMENT '一周出现最多的夜间天气类型',
    tempreture_day_highest                  TINYINT         COMMENT '一周最高日间气温',
    tempreture_day_highest_last_week        TINYINT         COMMENT '上周最高日间气温',
    tempreture_day_highest_gap              TINYINT         COMMENT '这周和上周最高日间温差',
    tempreture_day_lowest                   TINYINT         COMMENT '一周最低日间气温',
    tempreture_day_lowest_last_week         TINYINT         COMMENT '上周最低日间气温',
    tempreture_day_lowest_gap               TINYINT         COMMENT '这周和上周最低日间温差',
    tempreture_day_avg                      DECIMAL(18, 2)  COMMENT '一周平均日间气温',
    tempreture_day_avg_last_week            DECIMAL(18, 2)  COMMENT '上周平均日间气温',
    tempreture_day_avg_gap                  DECIMAL(18, 2)  COMMENT '这周和上周的平均日间气温温差',
    tempreture_day_gap                      TINYINT         COMMENT '一周最高最低日间温差',
    tempreture_day_gap_last_week            TINYINT         COMMENT '上周最高最低日间温差',
    tempreture_night_highest                TINYINT         COMMENT '一周最高夜间气温',
    tempreture_night_highest_last_week      TINYINT         COMMENT '上周最高夜间气温',
    tempreture_night_highest_gap            TINYINT         COMMENT '这周和上周最高夜间温差',
    tempreture_night_lowest                 TINYINT         COMMENT '一周最低夜间气温',
    tempreture_night_lowest_last_week       TINYINT         COMMENT '上周最低夜间气温',
    tempreture_night_lowest_gap             TINYINT         COMMENT '这周和上周最低夜间温差',
    tempreture_night_avg                    DECIMAL(18, 2)  COMMENT '一周平均夜间气温',
    tempreture_night_avg_last_week          DECIMAL(18, 2)  COMMENT '上周平均夜间气温',
    tempreture_night_avg_gap                DECIMAL(18, 2)  COMMENT '这周和上周平均夜间气温温差',
    tempreture_night_gap                    TINYINT         COMMENT '一周最高最低夜间温差',
    tempreture_night_gap_last_week          TINYINT         COMMENT '上周最高最低夜间温差',
    tempreture_avg_gap                      DECIMAL(18, 2)  COMMENT '一周日间夜间平均温差',
    tempreture_avg_gap_last_week            DECIMAL(18, 2)  COMMENT '上周日间夜间平均温差',
    -- 价格相关
    retail_amount_mean                      DECIMAL(30, 2)  COMMENT '平均零售价',
    retail_amount_mean_gap_with_store       DECIMAL(18, 2)  COMMENT 'skc零售价与门店8周内平均零售价的差值',
    discount_rate_mean_last_week            DECIMAL(20, 2)  COMMENT '上周平均折扣率',
    discount_rate_mean_last_2week           DECIMAL(20, 2)  COMMENT '上2周平均折扣率',
    discount_rate_mean_gap_1_2              DECIMAL(18, 2)  COMMENT '上周和上2周的平均折扣率的差值',
    skc_con_sale_rate_last_week             DECIMAL(20, 2)  COMMENT '上周skc连销率',
    skc_con_sale_rate_last_2week            DECIMAL(20, 2)  COMMENT '上2周skc连销率',
    skc_con_sale_rate_gap_1_2               DECIMAL(18, 2)  COMMENT '上周和上2周的skc连销率的差值',
    sales_qty_last_week                     INTEGER         COMMENT '上周销量',
    sales_qty_last_2week                    INTEGER         COMMENT '上2周销量',
    sales_qty_gap_1_2                       INTEGER         COMMENT '上周和上2周的销量差值',
    sales_qty                               INTEGER         COMMENT '实际销量',
    sales_qty_type                          VARCHAR         COMMENT '销量类型'
);


INSERT INTO ads_mms.training_data_store_skc_week_merge
    SELECT
        tr_str_skc_w.store_code,
        tr_str_skc_w.skc_code,
        tr_str_skc_w.year_code,
        tr_str_skc_w.week_code,
        tr_str_skc_w.year_week_code,
        tr_str_skc_w.prev_year_week_code,
        tr_str_skc_w.interval_weeks_to_prev,
        tr_str_skc_w.list_dates_year_code,
        tr_str_skc_w.list_dates_week_code,
        tr_str_skc_w.list_dates_year_week_code,
        tr_str_skc_w.interval_weeks_to_list,
        -- 门店相关
        tr_str_skc_w.city_name,
        tr_str_skc_w.area_code,
        tr_str_skc_w.sales_channel,
        tr_str_skc_w.store_type,
        tr_str_skc_w.store_level,
        tr_str_skc_w.store_retail_amount_highest_8week,
        tr_str_skc_w.store_retail_amount_lowest_8week,
        tr_str_skc_w.store_retail_amount_mean_8week,
        tr_str_skc_w.store_retail_amount_gap_8week,
        tr_str_skc_w.store_sales_amount_highest_8week,
        tr_str_skc_w.store_sales_amount_lowest_8week,
        tr_str_skc_w.store_sales_amount_mean_8week,
        tr_str_skc_w.store_sales_amount_gap_8week,
        tr_str_skc_w.store_discount_rate_mean_8week,
        -- skc相关
        tr_str_skc_w.main_cate,
        tr_str_skc_w.sub_cate,
        tr_str_skc_w.leaf_cate,
        tr_str_skc_w.leaf_cate_retail_amount_highest_8week,
        tr_str_skc_w.leaf_cate_retail_amount_lowest_8week,
        tr_str_skc_w.leaf_cate_retail_amount_mean_8week,
        tr_str_skc_w.leaf_cate_retail_amount_gap_8week,
        tr_str_skc_w.leaf_cate_sales_amount_highest_8week,
        tr_str_skc_w.leaf_cate_sales_amount_lowest_8week,
        tr_str_skc_w.leaf_cate_sales_amount_mean_8week,
        tr_str_skc_w.leaf_cate_sales_amount_gap_8week,
        tr_str_skc_w.leaf_cate_discount_rate_mean_8week,
        tr_str_skc_w.color_code,
        tr_str_skc_w.lining,
        tr_str_skc_w.customer_level_1_last_week,
        tr_str_skc_w.customer_level_2_last_week,
        tr_str_skc_w.customer_level_3_last_week,
        tr_str_skc_w.customer_level_1_proportion_last_week,
        tr_str_skc_w.customer_level_2_proportion_last_week,
        tr_str_skc_w.customer_level_3_proportion_last_week,
        tr_str_skc_w.customer_level_1_last_2week,
        tr_str_skc_w.customer_level_2_last_2week,
        tr_str_skc_w.customer_level_3_last_2week,
        tr_str_skc_w.customer_level_1_proportion_last_2week,
        tr_str_skc_w.customer_level_2_proportion_last_2week,
        tr_str_skc_w.customer_level_3_proportion_last_2week,
        tr_str_skc_w.customer_level_1_gap,
        tr_str_skc_w.customer_level_2_gap,
        tr_str_skc_w.customer_level_3_gap,
        tr_str_skc_w.special_day_type,
        -- 天气
        tr_str_skc_w.weather_day_most,
        tr_str_skc_w.weather_night_most,
        tr_str_skc_w.tempreture_day_highest,
        tr_str_skc_w.tempreture_day_highest_last_week,
        tr_str_skc_w.tempreture_day_highest_gap,
        tr_str_skc_w.tempreture_day_lowest,
        tr_str_skc_w.tempreture_day_lowest_last_week,
        tr_str_skc_w.tempreture_day_lowest_gap,
        tr_str_skc_w.tempreture_day_avg,
        tr_str_skc_w.tempreture_day_avg_last_week,
        tr_str_skc_w.tempreture_day_avg_gap,
        tr_str_skc_w.tempreture_day_gap,
        tr_str_skc_w.tempreture_day_gap_last_week,
        tr_str_skc_w.tempreture_night_highest,
        tr_str_skc_w.tempreture_night_highest_last_week,
        tr_str_skc_w.tempreture_night_highest_gap,
        tr_str_skc_w.tempreture_night_lowest,
        tr_str_skc_w.tempreture_night_lowest_last_week,
        tr_str_skc_w.tempreture_night_lowest_gap,
        tr_str_skc_w.tempreture_night_avg,
        tr_str_skc_w.tempreture_night_avg_last_week,
        tr_str_skc_w.tempreture_night_avg_gap,
        tr_str_skc_w.tempreture_night_gap,
        tr_str_skc_w.tempreture_night_gap_last_week,
        tr_str_skc_w.tempreture_avg_gap,
        tr_str_skc_w.tempreture_avg_gap_last_week,
        -- 价格相关
        tr_str_skc_w.retail_amount_mean,
        tr_str_skc_w.retail_amount_mean_gap_with_store,
        tr_str_skc_w.discount_rate_mean_last_week,
        tr_str_skc_w.discount_rate_mean_last_2week,
        tr_str_skc_w.discount_rate_mean_gap_1_2,
        tr_str_skc_w.skc_con_sale_rate_last_week,
        tr_str_skc_w.skc_con_sale_rate_last_2week,
        tr_str_skc_w.skc_con_sale_rate_gap_1_2,
        tr_str_skc_w.sales_qty_last_week,
        tr_str_skc_w.sales_qty_last_2week,
        tr_str_skc_w.sales_qty_gap_1_2,
        tr_str_skc_w.sales_qty,

        cast((
            CASE
            WHEN tr_str_skc_w.sales_qty = 1 THEN '1'
            WHEN tr_str_skc_w.sales_qty = 2 THEN '2'
            WHEN tr_str_skc_w.sales_qty IN (3, 4, 5) THEN '3-5'
            ELSE '>5'
            END) AS VARCHAR)

    FROM
        cdm_mms.training_data_store_skc_week_merge tr_str_skc_w;
