INSERT INTO ads_mms.training_data_store_skc_week_merge
    SELECT
        tr_str_skc_w.store_code,
        tr_str_skc_w.skc_code,
        tr_str_skc_w.year_code,
        tr_str_skc_w.week_code,
        tr_str_skc_w.year_week_code,
        tr_str_skc_w.prev_year_week_code,
        tr_str_skc_w.interval_weeks_to_prev,
        tr_str_skc_w.list_dates_year_code,
        tr_str_skc_w.list_dates_week_code,
        tr_str_skc_w.list_dates_year_week_code,
        tr_str_skc_w.interval_weeks_to_list,
        -- 门店相关
        tr_str_skc_w.city_name,
        tr_str_skc_w.area_code,
        tr_str_skc_w.sales_channel,
        tr_str_skc_w.store_type,
        tr_str_skc_w.store_level,
        tr_str_skc_w.store_retail_amount_highest_8week,
        tr_str_skc_w.store_retail_amount_lowest_8week,
        tr_str_skc_w.store_retail_amount_mean_8week,
        tr_str_skc_w.store_retail_amount_gap_8week,
        tr_str_skc_w.store_sales_amount_highest_8week,
        tr_str_skc_w.store_sales_amount_lowest_8week,
        tr_str_skc_w.store_sales_amount_mean_8week,
        tr_str_skc_w.store_sales_amount_gap_8week,
        tr_str_skc_w.store_discount_rate_mean_8week,
        -- skc相关
        tr_str_skc_w.main_cate,
        tr_str_skc_w.sub_cate,
        tr_str_skc_w.leaf_cate,
        tr_str_skc_w.leaf_cate_retail_amount_highest_8week,
        tr_str_skc_w.leaf_cate_retail_amount_lowest_8week,
        tr_str_skc_w.leaf_cate_retail_amount_mean_8week,
        tr_str_skc_w.leaf_cate_retail_amount_gap_8week,
        tr_str_skc_w.leaf_cate_sales_amount_highest_8week,
        tr_str_skc_w.leaf_cate_sales_amount_lowest_8week,
        tr_str_skc_w.leaf_cate_sales_amount_mean_8week,
        tr_str_skc_w.leaf_cate_sales_amount_gap_8week,
        tr_str_skc_w.leaf_cate_discount_rate_mean_8week,
        tr_str_skc_w.color_code,
        tr_str_skc_w.lining,
        tr_str_skc_w.customer_level_1_last_week,
        tr_str_skc_w.customer_level_2_last_week,
        tr_str_skc_w.customer_level_3_last_week,
        tr_str_skc_w.customer_level_1_proportion_last_week,
        tr_str_skc_w.customer_level_2_proportion_last_week,
        tr_str_skc_w.customer_level_3_proportion_last_week,
        tr_str_skc_w.customer_level_1_last_2week,
        tr_str_skc_w.customer_level_2_last_2week,
        tr_str_skc_w.customer_level_3_last_2week,
        tr_str_skc_w.customer_level_1_proportion_last_2week,
        tr_str_skc_w.customer_level_2_proportion_last_2week,
        tr_str_skc_w.customer_level_3_proportion_last_2week,
        tr_str_skc_w.customer_level_1_gap,
        tr_str_skc_w.customer_level_2_gap,
        tr_str_skc_w.customer_level_3_gap,
        tr_str_skc_w.special_day_type,
        -- 天气
        tr_str_skc_w.weather_day_most,
        tr_str_skc_w.weather_night_most,
        tr_str_skc_w.tempreture_day_highest,
        tr_str_skc_w.tempreture_day_highest_last_week,
        tr_str_skc_w.tempreture_day_highest_gap,
        tr_str_skc_w.tempreture_day_lowest,
        tr_str_skc_w.tempreture_day_lowest_last_week,
        tr_str_skc_w.tempreture_day_lowest_gap,
        tr_str_skc_w.tempreture_day_avg,
        tr_str_skc_w.tempreture_day_avg_last_week,
        tr_str_skc_w.tempreture_day_avg_gap,
        tr_str_skc_w.tempreture_day_gap,
        tr_str_skc_w.tempreture_day_gap_last_week,
        tr_str_skc_w.tempreture_night_highest,
        tr_str_skc_w.tempreture_night_highest_last_week,
        tr_str_skc_w.tempreture_night_highest_gap,
        tr_str_skc_w.tempreture_night_lowest,
        tr_str_skc_w.tempreture_night_lowest_last_week,
        tr_str_skc_w.tempreture_night_lowest_gap,
        tr_str_skc_w.tempreture_night_avg,
        tr_str_skc_w.tempreture_night_avg_last_week,
        tr_str_skc_w.tempreture_night_avg_gap,
        tr_str_skc_w.tempreture_night_gap,
        tr_str_skc_w.tempreture_night_gap_last_week,
        tr_str_skc_w.tempreture_avg_gap,
        tr_str_skc_w.tempreture_avg_gap_last_week,
        -- 价格相关
        tr_str_skc_w.retail_amount_mean,
        tr_str_skc_w.retail_amount_mean_gap_with_store,
        tr_str_skc_w.discount_rate_mean_last_week,
        tr_str_skc_w.discount_rate_mean_last_2week,
        tr_str_skc_w.discount_rate_mean_gap_1_2,
        tr_str_skc_w.skc_con_sale_rate_last_week,
        tr_str_skc_w.skc_con_sale_rate_last_2week,
        tr_str_skc_w.skc_con_sale_rate_gap_1_2,
        tr_str_skc_w.sales_qty_last_week,
        tr_str_skc_w.sales_qty_last_2week,
        tr_str_skc_w.sales_qty_gap_1_2,
        tr_str_skc_w.sales_qty,

        cast((
            CASE
            WHEN tr_str_skc_w.sales_qty = 1 THEN '1'
            WHEN tr_str_skc_w.sales_qty = 2 THEN '2'
            WHEN tr_str_skc_w.sales_qty IN (3, 4, 5) THEN '3-5'
            ELSE '>5'
            END) AS VARCHAR)

    FROM
        cdm_mms.training_data_store_skc_week_merge tr_str_skc_w
    WHERE
        tr_str_skc_w.year_week_code > (SELECT max(year_week_code) FROM ads_mms.training_data_store_skc_week_merge);
